#!/usr/bin/env bash

choice=$(
  nmcli -t -f SSID dev wifi \
  | sed '/^$/d' \
  | sort -u \
  | wofi --insensitive --dmenu --prompt "Wi‑Fi:"
)

if [[ -n "$choice" ]]; then
  nmcli device wifi connect "$choice"
fi
