#!/bin/bash

if [ $# -ne 2 ]; then
    echo "Usage: $0 <output_file> <url>"
    exit 1
fi

if ! yt-dlp -o ~/Videos/$1.mp4 -f "bestvideo[height<=1080][ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" $2; then
    exit 1;
fi

echo "Succesfully downloaded $2 to ~/Videos/$1.mp4"
exit 0;